name: X to Discord Bot (Test)

on:
  schedule:
    # Run every hour (UTC)
    - cron: '0 * * * *'

  # Allow manual runs
  workflow_dispatch:
    inputs:
      test_user:
        description: "X username to test (leave empty for production)"
        required: false
        default: ""
  

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Restore last tweet cache
        uses: actions/cache@v4
        with:
            path: last_tweet.json
            key: last-tweet-${{ github.repository }}
            
      - name: Run bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TEST_USER: ${{ github.event.inputs.test_user }}
          X_COOKIES: ${{ secrets.X_COOKIES }}
        run: node bot.js

      - name: Save last tweet cache
        uses: actions/cache@v4
        with:
          path: last_tweet.json
          key: last-tweet-${{ github.repository }}

